# kate: indent-width 2;

clone_depth: 1

os: Visual Studio 2015

environment:
  matrix:
  - TARGET: desktop
    COMPILER: msvc
  - TARGET: desktop
    COMPILER: mingw
  - TARGET: emscripten
    TARGET_GLES2: ON
  - TARGET: emscripten
    TARGET_GLES2: OFF
  - TARGET: rt
    TARGET_GLES2: ON
  - TARGET: rt
    TARGET_GLES2: OFF

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- cinst ninja
- set PATH=C:/tools/ninja;%PATH%
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" cinst mingw /f >nul
- IF "%TARGET%" == "emscripten" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\emsdk-1.35.0-full-64bit.exe appveyor DownloadFile https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-1.35.0-full-64bit.exe
- IF "%TARGET%" == "emscripten" emsdk-1.35.0-full-64bit.exe /S /D=C:\emscripten

# OpenAL
- IF "%TARGET%" == "desktop" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\openal-soft-1.17.2-bin.zip appveyor DownloadFile http://kcat.strangesoft.net/openal-binaries/openal-soft-1.17.2-bin.zip
- IF "%TARGET%" == "desktop" 7z x openal-soft-1.17.2-bin.zip && ren openal-soft-1.17.2-bin openal && echo [General] > %APPDATA%/alsoft.ini & echo drivers=null >> %APPDATA%/alsoft.ini
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" ren openal\bin\Win32\soft_oal.dll OpenAL32.dll
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" ren openal\bin\Win64\soft_oal.dll OpenAL32.dll

# SDL2
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-devel-2.0.4-VC.zip appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" 7z x SDL2-devel-2.0.4-VC.zip && ren SDL2-2.0.4 SDL
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-devel-2.0.4-mingw.tar.gz appveyor DownloadFile http://libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" 7z x SDL2-devel-2.0.4-mingw.tar.gz & 7z x SDL2-devel-2.0.4-mingw.tar & ren SDL2-2.0.4 SDL

build_script:
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" call package\ci\appveyor-desktop.bat
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" call package\ci\appveyor-desktop-mingw.bat
- IF "%TARGET%" == "emscripten" call package\ci\appveyor-emscripten.bat
- IF "%TARGET%" == "rt" call package\ci\appveyor-rt.bat

cache:
- SDL2-devel-2.0.4-VC.zip
- SDL2-devel-2.0.4-mingw.zip
- openal-soft-1.17.2-bin.zip
- emsdk-1.35.0-full-64bit.exe
